apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: superset
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: superset
    spec:
      containers:
      - image: amancevice/superset:latest
        name: superset
        resources: {}
status: {}
