apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: superset
  name: superset
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: superset
  type: NodePort
status:
  loadBalancer: {}
